# Generated by Django 2.2.20 on 2021-09-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinelaundry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='static/pics/%y/%m/%d/'),
        ),
    ]
